import { mkdir, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

// OSC 133 semantic markers: the shell reports where each command begins and
// ends. Without them a terminal's state can only be inferred from output, and a
// command that takes a while without printing anything is indistinguishable from
// an idle shell.
const ZSHRC = `# Generated by voice-master. Do not edit: rewritten on every start.
# Forwards the user's configuration and adds OSC 133 markers.

VM_ORIG="\${VM_ZDOTDIR_ORIG:-$HOME}"
[[ -f "$VM_ORIG/.zshrc" ]] && source "$VM_ORIG/.zshrc"

autoload -Uz add-zsh-hook 2>/dev/null && {
  _vm_preexec() { printf '\\033]133;C\\007' }
  _vm_precmd()  { local code=$?; printf '\\033]133;D;%s\\007' "$code" }
  add-zsh-hook preexec _vm_preexec
  add-zsh-hook precmd  _vm_precmd
}
`;

// zsh resolves .zshenv and .zprofile inside ZDOTDIR; without these forwards,
// pointing ZDOTDIR elsewhere would leave the user's configuration out.
const ZSHENV = `VM_ORIG="\${VM_ZDOTDIR_ORIG:-$HOME}"
[[ -f "$VM_ORIG/.zshenv" ]] && source "$VM_ORIG/.zshenv"
`;

const ZPROFILE = `VM_ORIG="\${VM_ZDOTDIR_ORIG:-$HOME}"
[[ -f "$VM_ORIG/.zprofile" ]] && source "$VM_ORIG/.zprofile"
`;

export interface ShellIntegration {
  dir: string;
  env: Record<string, string>;
}

/**
 * Prepares a private ZDOTDIR that forwards to the user's configuration and adds
 * the command markers. No user file is modified.
 *
 * Returns null for shells other than zsh: bash and fish use different hooks and
 * are not implemented yet.
 */
export async function prepareShellIntegration(
  stateDir: string,
  shell: string,
): Promise<ShellIntegration | null> {
  if (!shell.endsWith("zsh")) return null;

  const dir = path.join(stateDir, "shell-integration", "zsh");
  await mkdir(dir, { recursive: true });

  await Promise.all([
    writeFile(path.join(dir, ".zshrc"), ZSHRC, "utf8"),
    writeFile(path.join(dir, ".zshenv"), ZSHENV, "utf8"),
    writeFile(path.join(dir, ".zprofile"), ZPROFILE, "utf8"),
  ]);

  return {
    dir,
    env: {
      ZDOTDIR: dir,
      VM_ZDOTDIR_ORIG: process.env["ZDOTDIR"] ?? os.homedir(),
    },
  };
}

/**
 * Variables the official Claude Code plugin for Warp checks before emitting its
 * structured notifications (`should-use-structured.sh`). The transport is OSC 777
 * over the pty's stdout, not a private Warp channel: by declaring protocol
 * compatibility, the plugin emits and this application receives it just the same.
 *
 * The version is a hand-pinned value. If Warp tightens the check or the payload
 * format changes, this stops working silently and the screen detector is left as
 * the fallback.
 */
export const CLI_AGENT_ENV: Record<string, string> = {
  WARP_CLI_AGENT_PROTOCOL_VERSION: "1",
  WARP_CLIENT_VERSION: "v0.2026.07.29.09.05.stable_02",
};

// Variables Claude Code exports to its child processes. If the application is
// launched from a Claude Code session, inheriting them makes every terminal it
// opens look like a nested session: among other effects, the child-session marker
// disables transcript saving, and without a transcript the end-of-turn events
// arrive with neither the query nor the answer.
const AGENT_VARS = [
  "CLAUDECODE",
  "CLAUDE_CODE_CHILD_SESSION",
  "CLAUDE_CODE_ENTRYPOINT",
  "CLAUDE_CODE_EXECPATH",
  "CLAUDE_CODE_SESSION_ID",
  "CLAUDE_CODE_VERSION",
  "CLAUDE_EFFORT",
  "CLAUDE_PID",
];

/** Copies the environment, dropping what a new terminal must not inherit. */
export function sanitizeEnv(source: NodeJS.ProcessEnv): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [key, value] of Object.entries(source)) {
    if (value === undefined || AGENT_VARS.includes(key)) continue;
    out[key] = value;
  }
  return out;
}
